version: "3.8"

services:
  spring:
    build: ./pcproject
    ports:
      - "8080:8080"
    environment:
    - TZ=Asia/Seoul
    - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    depends_on:
      - db
      - back_py

  back_py:
    build: ./back_py
    container_name: back_py
    ports:
      - "8001:8000"  # FastAPI 외부 노출 포트
    volumes:
      - ./back_py:/app
      - ./data:/app/data
      - ./chroma:/app/chroma
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ=Asia/Seoul
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project
      TZ: Asia/Seoul
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
