<<<<<<< HEAD
version: "3.8"
=======
#version: "3.8"
>>>>>>> 0d8dc81 (back)

services:
  spring:
    build: ./pcproject
<<<<<<< HEAD
    ports:
      - "8080:8080"
    environment:
    - TZ=Asia/Seoul
    - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    depends_on:
      - db
      - back_py
=======
    env_file:
      - OPENAI_API_KEY.env
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/project?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      db:
        condition: service_healthy
>>>>>>> 0d8dc81 (back)

  back_py:
    build: ./back_py
    container_name: back_py
<<<<<<< HEAD
=======
    env_file:
      - OPENAI_API_KEY.env
>>>>>>> 0d8dc81 (back)
    ports:
      - "8001:8000"  # FastAPI 외부 노출 포트
    volumes:
      - ./back_py:/app
    environment:
<<<<<<< HEAD
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ = Asia/Seoul
    depends_on:
      - db

  db:
    image: mysql:8
=======
      - TZ=Asia/Seoul
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
>>>>>>> 0d8dc81 (back)
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project
      TZ: Asia/Seoul
    command: [
      "--character-set-server=utf8mb4",
<<<<<<< HEAD
      "--collation-server=utf8mb4_unicode_ci",
      "--character-set-client-handshake=FALSE"
=======
      "--collation-server=utf8mb4_unicode_ci"
>>>>>>> 0d8dc81 (back)
    ]
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
