services:
  spring:
    build: ./pcproject
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/project?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      db:
        condition: service_healthy
      back_py:
        condition: service_started

  back_py:
    build: ./back_py
    container_name: back_py
    ports:
      - "8001:8000"  # FastAPI 외부 노출 포트
    volumes:
      - ./back_py:/app
      - ./data:/app/data
      - ./chroma:/app/chroma
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ=Asia/Seoul
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project
      TZ: Asia/Seoul
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: redis
    command: >
      sh -c "redis-server
             --appendonly yes         
             --save ''               
             --maxmemory 512mb         
             --maxmemory-policy allkeys-lru  
             --protected-mode no"      
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: always